baseurl = "https://ahmethusrevaltinbasak.github.io/ustad/"  # Include trailing slash
title = "Ahmed Hüsrev Altınbaşak"
theme = "hugo-swift-theme"
author = "Hayrat Vakfı"
canonifyurls = true
paginate = 20
toc = true
publishDir = "docs"
disqusShortname = "disqus_dSP26bU66V"

[taxonomies]
  tag = "tags"
  category = "categories"

[outputs]
  home = ["HTML", "RSS", "JSON"]
