baseurl = "https://ahmethusrevaltinbasak.github.io/ustad/"  # Include trailing slash
title = "Ahmed Hüsrev Altınbaşak"
description = "Üstad Said-i Nursi&#039;nin Hayru&#039;l-Halefi"
theme = "hugo-swift-theme"
author = "Hayrat Vakfı"
canonifyurls = true
paginate = 20
toc = true
publishDir = "docs"
disqusShortname = "https-ahmethusrevaltinbasak-github-io-ustad-1"

[taxonomies]
  tag = "tags"
  category = "categories"

[outputs]
  home = ["HTML", "RSS", "JSON"]
