baseurl = "https://example.com/"  # Include trailing slash
title = "Ahmed Hüsrev Altınbaşak"
theme = "hugo-swift-theme"
author = "Hayrat Vakfı"
canonifyurls = true
paginate = 20
toc = true
publishDir = "docs"

[taxonomies]
  tag = "tags"
  category = "categories"

[outputs]
  home = ["HTML", "RSS", "JSON"]
